# Generated by Django 4.2.11 on 2024-03-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='img_detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
