# Generated by Django 4.2.11 on 2024-03-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_img_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img_detail',
            field=models.TextField(max_length=50),
        ),
    ]
