# Generated by Django 4.2.11 on 2024-03-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_gallery_options_gallery_likes_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='feature_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='user_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
