# Generated by Django 4.2.11 on 2024-03-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_comment_feature_img_alter_gallery_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='feature_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
