# Generated by Django 4.2.11 on 2024-03-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-created_on']},
        ),
    ]
