# Generated by Django 4.2.11 on 2024-03-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_remove_comment_name_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='difficulty_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
