# Generated by Django 4.2.11 on 2024-03-20 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0008_route_difficulty_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='route_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
