# Generated by Django 4.2.11 on 2024-03-20 16:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_comment_feature_img_alter_route_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='feature_img',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
