# Generated by Django 4.2.11 on 2024-03-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_route_feature_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
