# Generated by Django 4.2.11 on 2024-03-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_wainwright'),
    ]

    operations = [
        migrations.AddField(
            model_name='wainwright',
            name='completed',
            field=models.IntegerField(choices=[(0, 'Not Complete'), (1, 'Completed')], default=0),
        ),
    ]
